### ISSUE TITLE
Rotation Direction

### ISSUE THREAD

**Issue by IMPMAC** [Arkounay/2D-Canvas-Image-Particles#1]
Hi, I am playing around with the random rotation mode. I was wondering how I could have it rotate both clockwise and anti-clockwise

Many Thanks

**Comment by Arkounay** [comment]
Hi, this was indeed impossible but it's an important feature so I just added it.
Now you can set negative rotation values with a positive one and both rotations will apply (e.g: `rotationSpeed: [-50, 50],`). There is now also a way to force a minimum rotation speed with the new option `minimumRotationSpeed`.
